name: Build project

on: [push, pull_request]

jobs:
  buildForWin:
    name: Build for win
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneWindows64
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform:  StandaloneWindows64
      - uses: actions/upload-artifact@v2
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
