name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build-unitybundle:
    name: Build Unity Asset Bundles
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
    # Cache
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: |
          unity/Library
        key: Library-Unity-KSP
    # Build
    - name: Build project
      uses: webbertakken/unity-builder@v1.0
      with:
        projectPath: unity
        unityVersion: 2019.2.2f1
        targetPlatform: StandaloneWindows
        buildMethod: AssetBundleBuilder.RunAssetBuild
    # Output 
    - uses: actions/upload-artifact@v1
      with:
        name: AssetBundle
        path: GameData
