name: Build and Upload to cloud  

on:
  pull_request: {}
  push: { branches: [master] }
 
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
jobs:

  BuildWindows:
    name: Build and Upload the Project for Windows  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
        
    steps:
     
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
           lfs: true
     
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
 
      # Build for win
      - name: Build project for windows
        uses: webbertakken/unity-builder@v0.10
        with:
          
           buildName: InteractiveWriting-Windows v${{ github.run_number }}
           unityVersion: 2019.2.2f1
           targetPlatform : 
            StandaloneWindows64

         
      # Output for win
      - uses: actions/upload-artifact@v1
        with:
          name: WinBuiltProject
          path: build

      # Upload the build to Google Drive    
      - name: Upload Win build to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
           target: build     
           name: InteractiveWriting-Win v${{ github.run_number }}
           credentials: ${{ secrets.CREDENTIALS }}
           folder: ${{ secrets.DRIVE_FOLDER_ID }}
